name: quotes
description: "Quotes"

publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_riverpod: ^2.5.3
  freezed_annotation: ^2.4.4
  auto_route: ^9.2.2
  share_plus: ^10.1.0
  logger: ^2.4.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/quotes.jpg

flutter_native_splash:
  color: "#42a5f5"
  image: assets/quotes.jpg
  android: true
  ios: true
  android_12: 
    color: "#42a5f5"
    image: assets/quotes.jpg
